language: swift
osx_image: xcode9.3
xcode_workspace: Bookshelf.xcworkspace
xcode_scheme: Bookshelf
before_install:
- brew update
- brew install tree
- sudo gem install cocoapods
- pod repo update
- tree -L 1
- pod install
- tree -L 1
