language: swift
osx_image: xcode9.3
before_install:
- brew update
- brew install tree
- sudo gem install cocoapods
- pod repo update
- tree -L 1
- pod install
- tree -L 1
script:
- xcodebuild test -workspace Bookshelf.xcworkspace -scheme Bookshelf -destination 'platform=iOS Simulator,name=iPhone X,OS=11.3' | xcpretty 
