language: objective-c
osx_image: xcode8

env:
  - PLATFORM=iOS  SDK=iphonesimulator  UUID='9793E592-F0FF-4C4A-BEEF-FDD50A67E8C1'

install:
  - carthage bootstrap --platform $PLATFORM

script:
  - if [ -n "$UUID" ]; then xcrun instruments -w "$UUID" || true; sleep 15; fi
  - set -o pipefail && xcodebuild -scheme PMKAssetsLibrary -sdk $SDK -destination "id=$UUID" clean build build-for-testing | xcpretty || true
  - set -o pipefail && xcodebuild -scheme PMKAssetsLibrary -sdk $SDK -destination "id=$UUID" test | xcpretty
