//
//  KCSFileUploadViewController.swift
//  KinveyKit
//
//  Created by Victor Barros on 2015-07-24.
//  Copyright (c) 2015 Kinvey. All rights reserved.
//

import UIKit

class FileUploadViewController: UIViewController, UITextFieldDelegate {

    @IBOutlet weak var timesTextField: UITextField!
    @IBOutlet weak var timesStepper: UIStepper!
    @IBOutlet weak var counterLabel: UILabel!
    
    var counter = 0
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        self.valueChangedStepper(self.timesStepper)
        
        KCSClient.sharedClient().initializeKinveyServiceForAppKey(
            "kid_-1WAs8Rh2",
            withAppSecret: "2f355bfaa8cb4f7299e914e8e85d8c98",
            usingOptions: nil
        )
        
        self.counterLabel.text = "Loading..."
        
        KCSUser.createAutogeneratedUser(
            nil,
            completion: { (user: KCSUser!, error: NSError!, actionResult: KCSUserActionResult) -> Void in
                self.counterLabel.text = String(self.counter)
            }
        )
    }

    override func didReceiveMemoryWarning() {
        super.didReceiveMemoryWarning()
        // Dispose of any resources that can be recreated.
    }
    

    /*
    // MARK: - Navigation

    // In a storyboard-based application, you will often want to do a little preparation before navigation
    override func prepareForSegue(segue: UIStoryboardSegue, sender: AnyObject?) {
        // Get the new view controller using segue.destinationViewController.
        // Pass the selected object to the new view controller.
    }
    */
    
    func textField(textField: UITextField, shouldChangeCharactersInRange range: NSRange, replacementString string: String) -> Bool {
        let newString = (textField.text! as NSString).stringByReplacingCharactersInRange(range, withString: string)
        
        if (textField == timesTextField) {
            valueChangedTimes(newString)
        }
        
        return true
    }
    
    func valueChangedTimes(string: String) {
        if let int = Int(string) {
            timesStepper.value = Double(int)
        }
    }
    
    @IBAction func valueChangedStepper(sender: AnyObject) {
        timesTextField.text = String(format:"%d", Int(timesStepper.value))
    }

    @IBAction func touchUpInsideUpload(sender: AnyObject) {
        let url = NSBundle.mainBundle().URLForResource("mavericks", withExtension: "jpg")
        
        for _ in 1...Int(timesStepper.value) {
            KCSFileStore.uploadFile(
                url,
                options: nil,
                completionBlock: { (file: KCSFile!, error: NSError!) -> Void in
                    self.counterLabel.text = String(++self.counter)
                },
                progressBlock: nil
            )
        }
    }
}
