//
//  User2Tests.m
//  KinveyKit
//
//  Created by Michael Katz on 12/11/13.
//  Copyright (c) 2013-2015 Kinvey. All rights reserved.
//
// This software is licensed to you under the Kinvey terms of service located at
// http://www.kinvey.com/terms-of-use. By downloading, accessing and/or using this
// software, you hereby accept such terms of service  (and any agreement referenced
// therein) and agree that you have read, understand and agree to be bound by such
// terms of service and are of legal age to agree to such terms with Kinvey.
//
// This software contains valuable confidential and proprietary information of
// KINVEY, INC and is subject to applicable licensing agreements.
// Unauthorized reproduction, transmission or distribution of this file and its
// contents is a violation of applicable laws.
//


#import <XCTest/XCTest.h>

#import "KinveyUserService.h"
#import "TestUtils2.h"
#import "KinveyCoreInternal.h"
#import "KinveyDataStoreInternal.h"

#import "KCSHiddenMethods.h"
#import "KCSDataStore.h"

@interface User2Tests : KCSTestCase

@end

@implementation User2Tests

- (void)setUp
{
    [super setUp];
    [self setupKCS:NO];
}

- (void) testAutoBasic
{
    __weak __block XCTestExpectation* expectationGenerateUser = [self expectationWithDescription:@"generateUser"];
    __block id createdUser = nil;
    [KCSUser2 createAutogeneratedUser:nil completion:^(id<KCSUser2> user, NSError *error) {
        KTAssertNoError
        XCTAssertNotNil(user, @"should have a user");
//        XCTAssertTrue([user isKindOfClass:[KCSUser2 class]], @"should be a user object");
        
        XCTAssertTrue([NSThread isMainThread]);
        
        createdUser = user;
        
        [expectationGenerateUser fulfill];
    }];
    [self waitForExpectationsWithTimeout:30 handler:^(NSError *error) {
        expectationGenerateUser = nil;
    }];
    
    id activeUser = [KCSUser2 activeUser];
    XCTAssertNotNil(activeUser, @"should have an activeUser");
    XCTAssertEqualObjects(activeUser, createdUser, @"should match the created user");
}

- (void) testAutoOptions
{
    __weak __block XCTestExpectation* expectationGenerateUser = [self expectationWithDescription:@"generateUser"];
    __block id createdUser = nil;
    [KCSUser2 createAutogeneratedUser:@{KCSUserAttributeGivenname : @"Fred",
                                        KCSUserAttributeSurname : @"Fredson",
                                        KCSUserAttributeEmail : @"fred@fredson.com"
                                        } completion:^(id<KCSUser2> user, NSError *error)
    {
        KTAssertNoError
        XCTAssertNotNil(user, @"should have a user");
//        XCTAssertTrue([user isKindOfClass:[KCSUser2 class]], @"should be a user object");

        XCTAssertTrue([NSThread isMainThread]);

        createdUser = user;
        
        [expectationGenerateUser fulfill];
    }];
    [self waitForExpectationsWithTimeout:30 handler:^(NSError *error) {
        expectationGenerateUser = nil;
    }];
    
    KCSUser2* activeUser = [KCSUser2 activeUser];
    XCTAssertNotNil(activeUser, @"should have an activeUser");
    XCTAssertEqualObjects(activeUser, createdUser, @"should match the created user");
    XCTAssertEqualObjects(activeUser.email, @"fred@fredson.com", @"should be set");
    XCTAssertEqualObjects(activeUser.surname, @"Fredson", @"should be set");
    XCTAssertEqualObjects(activeUser.givenName, @"Fred", @"should be set");
}

- (void) testNamedBasic
{
    __weak __block XCTestExpectation* expectationGenerateUser = [self expectationWithDescription:@"generateUser"];
    __block id createdUser = nil;
    NSString* uname = [NSString UUID];
    NSString* password = [NSString UUID];
    [KCSUser2 createUserWithUsername:uname password:password fieldsAndValues:nil completion:^(id<KCSUser2> user, NSError *error) {
        KTAssertNoError
        XCTAssertNotNil(user, @"should have a user");
//        XCTAssertTrue([user isKindOfClass:[KCSUser2 class]], @"should be a user object");
        
        XCTAssertTrue([NSThread isMainThread]);
        
        createdUser = user;
        
        [expectationGenerateUser fulfill];
    }];
    [self waitForExpectationsWithTimeout:30 handler:^(NSError *error) {
        expectationGenerateUser = nil;
    }];
    
    id activeUser = [KCSUser2 activeUser];
    XCTAssertNotNil(activeUser, @"should have an activeUser");
    XCTAssertEqualObjects(activeUser, createdUser, @"should match the created user");
    XCTAssertEqualObjects([activeUser username], uname, @"usernames should match");
    
    XCTAssertTrue([KCSUser2 hasSavedCredentials], @"yes, please");
}

- (void) testNamedOptions
{
    __weak __block XCTestExpectation* expectationCreateUser = [self expectationWithDescription:@"createUser"];
    __block id createdUser = nil;
    NSString* uname = [NSString UUID];
    NSString* password = [NSString UUID];
    [KCSUser2 createUserWithUsername:uname password:password fieldsAndValues:@{KCSUserAttributeGivenname : @"Fred",
                                        KCSUserAttributeSurname : @"Fredson",
                                        KCSUserAttributeEmail : @"fred@fredson.com"
                                        } completion:^(id<KCSUser2> user, NSError *error)
    {
        KTAssertNoError
        XCTAssertNotNil(user, @"should have a user");
//        XCTAssertTrue([user isKindOfClass:[KCSUser2 class]], @"should be a user object");
        
        XCTAssertTrue([NSThread isMainThread]);
        
        createdUser = user;
        
        [expectationCreateUser fulfill];
    }];
    [self waitForExpectationsWithTimeout:30 handler:^(NSError *error) {
        expectationCreateUser = nil;
    }];
    
    KCSUser2* activeUser = [KCSUser2 activeUser];
    XCTAssertNotNil(activeUser, @"should have an activeUser");
    XCTAssertEqualObjects(activeUser, createdUser, @"should match the created user");
    XCTAssertEqualObjects(activeUser.email, @"fred@fredson.com", @"should be set");
    XCTAssertEqualObjects(activeUser.surname, @"Fredson", @"should be set");
    XCTAssertEqualObjects(activeUser.givenName, @"Fred", @"should be set");
    XCTAssertEqualObjects([activeUser username], uname, @"usernames should match");
    
    XCTAssertTrue([KCSUser2 hasSavedCredentials], @"yes, please");
}

- (void) testLogin
{
    NSString* username = [NSString UUID];
    NSString* password = [NSString UUID];
    
    __weak __block XCTestExpectation* expectationCreateUser = [self expectationWithDescription:@"createUser"];
    [KCSUser2 createUserWithUsername:username password:password fieldsAndValues:nil completion:^(id<KCSUser2> user, NSError *error) {
        KTAssertNoError
        XCTAssertNotNil(user, @"should have a user");
        
        XCTAssertTrue([NSThread isMainThread]);
        
        [expectationCreateUser fulfill];
    }];
    [self waitForExpectationsWithTimeout:30 handler:^(NSError *error) {
        expectationCreateUser = nil;
    }];
    
    [KCSUser2 logoutUser:[KCSUser2 activeUser]];
    KCSUser2* active = [KCSUser2 activeUser];
    XCTAssertNil(active, @"User should be cleared");
    
    __weak __block XCTestExpectation* expectationLogin = [self expectationWithDescription:@"login"];
    __block KCSUser2* loggedInUser;
    [KCSUser2 loginWithUsername:username password:password completion:^(id<KCSUser2> user, NSError *error) {
        KTAssertNoError
        XCTAssertNotNil(user, @"should get a user");
        
        XCTAssertTrue([NSThread isMainThread]);
        
        loggedInUser = user;
        
        [expectationLogin fulfill];
    }];
    [self waitForExpectationsWithTimeout:30 handler:^(NSError *error) {
        expectationLogin = nil;
    }];
    
    XCTAssertEqualObjects(loggedInUser, [KCSUser2 activeUser], @"should be active");
    
    [KCSUser2 logoutUser:loggedInUser];
}

- (void) testChangePassword
{
    
    NSString* username = [NSString UUID];
    NSString* password = [NSString UUID];
    
    __weak __block XCTestExpectation* expectationCreateUser = [self expectationWithDescription:@"createUser"];
    __block KCSUser2* thisUser = nil;
    [KCSUser2 createUserWithUsername:username password:password fieldsAndValues:nil completion:^(id<KCSUser2> user, NSError *error) {
        KTAssertNoError
        XCTAssertNotNil(user, @"should have a user");
        
        XCTAssertTrue([NSThread isMainThread]);
        
        thisUser = user;
        
        [expectationCreateUser fulfill];
    }];
    [self waitForExpectationsWithTimeout:30 handler:^(NSError *error) {
        expectationCreateUser = nil;
    }];
    
    NSString* newPassword = [NSString UUID];
    
    __weak __block XCTestExpectation* expectationChangePassword = [self expectationWithDescription:@"changePassword"];
    [KCSUser2 changePasswordForUser:thisUser password:newPassword completion:^(id<KCSUser2> user, NSError *error) {
        KTAssertNoError
        XCTAssertNotNil(user, @"Should get a user back");
        
        XCTAssertTrue([NSThread isMainThread]);
        
        [expectationChangePassword fulfill];
    }];
    [self waitForExpectationsWithTimeout:30 handler:^(NSError *error) {
        expectationChangePassword = nil;
    }];
    
    
    [KCSUser2 logoutUser:[KCSUser2 activeUser]];
    KCSUser2* active = [KCSUser2 activeUser];
    XCTAssertNil(active, @"User should be cleared");
 
    __block KCSUser2* newUser = nil;
    __weak __block XCTestExpectation* expectationLogin = [self expectationWithDescription:@"login"];
    [KCSUser2 loginWithUsername:username password:newPassword completion:^(id<KCSUser2> user, NSError *error) {
        KTAssertNoError;
        XCTAssertNotNil(user, @"should get user");
        
        XCTAssertTrue([NSThread isMainThread]);
        
        newUser = user;
        
        [expectationLogin fulfill];
    }];
    [self waitForExpectationsWithTimeout:30 handler:^(NSError *error) {
        expectationLogin = nil;
    }];
    XCTAssertEqualObjects(newUser, [KCSUser2 activeUser], @"should be the new active user");
}

- (void) doLogoutTest:(NSString*)errorCode
{
    NSString* token = [NSString UUID];
    NSString* uid = [NSString UUID];
    NSString* username = [NSString UUID];
    KCSUser2* aUsre = [[KCSUser2 alloc] init];
    aUsre.userId = uid;
    aUsre.username = username;
    [KCSKeychain2 setKinveyToken:token user:uid];
    [[KCSAppdataStore caches] cacheActiveUser:aUsre];
    
    KCSUser2* user = (id)[KCSUser activeUser];
    XCTAssertNotNil(user, @"should have a user");
    
    KCSMockServer* server = [KCSMockServer sharedServer];
    KCSNetworkResponse* response = [KCSNetworkResponse MockResponseWith:401 data:@{@"error":errorCode}];
    [server setResponse:response forRoute:@"/appdata/kid_test/R"];
    
    __weak __block XCTestExpectation* expectationQuery = [self expectationWithDescription:@"query"];
    KCSDataStore* store = [[KCSDataStore alloc] initWithCollection:@"R"];
    [store query:nil options:@{KCSRequestOptionUseMock : @YES} completion:^(NSArray* objects, NSError* error) {
        XCTAssertNotNil(error, @"should have an error");
        
        XCTAssertTrue([NSThread isMainThread]);
        
        [expectationQuery fulfill];
    }];
    
    [KCS_DDLog flushLog];
    
    [self waitForExpectationsWithTimeout:60 handler:^(NSError *error) {
        expectationQuery = nil;
    }];
}

- (void) test401Logout
{
    [self doLogoutTest:@"InvalidCredentials"];
    
    [[KCSUser activeUser] logout];
    
    KCSUser2* user = (id)[KCSUser activeUser];
    XCTAssertNil(user, @"user should be cleared");
}

- (void) testSettingStops401Logout
{
    NSDictionary* opts = [KCSClient2 sharedClient].configuration.options;
    opts = [opts dictionaryByAddingDictionary:@{KCS_KEEP_USER_LOGGED_IN_ON_BAD_CREDENTIALS : @YES}];
    [[KCSClient2 sharedClient].configuration setOptions:opts];
    
    [self doLogoutTest:@"InvalidCredentials"];
    
    KCSUser2* user = (id)[KCSUser activeUser];
    XCTAssertNotNil(user, @"user should still be around");
}


- (void) testUserLockedDown
{
    NSDictionary* opts = [KCSClient2 sharedClient].configuration.options;
    opts = [opts dictionaryByAddingDictionary:@{KCS_KEEP_USER_LOGGED_IN_ON_BAD_CREDENTIALS : @YES}];
    [[KCSClient2 sharedClient].configuration setOptions:opts];
    
    [self doLogoutTest:@"UserLockedDown"];
    
//    KCSUser2* user = (id)[KCSUser activeUser];
//    XCTAssertNil(user, @"user should be cleared");
}

- (void) testInsufficientCredentialsDoesNotLogoutUser
{
    [self doLogoutTest:@"InsufficientCredentials"];
    
    KCSUser2* user = (id)[KCSUser activeUser];
    XCTAssertNotNil(user, @"user should still be around");
}

@end
