#!/bin/sh
 
if [ $# -lt 2 ]
then
	echo "Usage: branch release-number ticket-number"
	exit
fi 
 
TAG="$1"
TICKET="$2"

TODAY=$(date "+%B\\x20%d,\\x20%Y")

#update readme
echo "-> updating readme..."
UPDATE_README_CMD="/usr/bin/perl -pi -e s/CHANGE-DATE/$TODAY/g KinveyKit/README.md"
$UPDATE_README_CMD
UPDATE_README_CMD="/usr/bin/perl -pi -e s/TAG-ME/$TAG/g KinveyKit/README.md"
$UPDATE_README_CMD

#update 
echo "-> updating header..."
UPDATE_VERSION_CMD="/usr/bin/perl -pi -e s/TAG-ME/$TAG/g KinveyKit/KinveyKit/KinveyVersion.h"
$UPDATE_VERSION_CMD

#update 
echo "-> updating appledoc..."
UPDATE_DOC_CMD="/usr/bin/perl -pi -e s/TAG-ME/$TAG/g KinveyKit/AppledocSettings.plist"
$UPDATE_DOC_CMD

#commit
echo "-> Commiting changes"
CI_COMMAND="svn ci -m \"update files for tag $TAG re #$TICKET\""
echo $CI_COMMAND

STATUS=$?
echo "Status: $STATUS"
if [ $STATUS -ne 0 ]
then
	echo "exit, error"
    exit
fi

echo "-> TAG in svn"

BRANCH_COMMAND="svn cp . https://subversion.assembla.com/svn/kinvey/ios-library/tags/$BRANCH/$TAG -m \"tag $TAG re #$TICKET\""
echo $BRANCH_COMMAND
