#!/bin/bash

## This is required for the tests to pass
open -a "iPhone Simulator.app"

echo "Sleeping for 10 seconds to let the simulator startup..."
sleep 10

## The output/input locations are passed in via command line
if [ $# -lt 1 ]
then
	echo "Usage: test-kinvey <KinveyKit Location> <clean first?>"
	exit
fi

if [ $# -lt 2 ]
then
    CLEAN="YES"
else
    CLEAN=$2
fi

KINVEYKITLOC=$1

echo "Building KinveyKit in ${KINVEYKITLOC}..."


# Future enhancment
#if [ -e "/usr/local/bin/ack" ]
#then
#    GREP="ack --flush --passthru --color --color-match=green \"^.*' passed \(.*\"  | ack --flush --passthru --color --color-match=red \"^.*' failed \(.*\""
#else
#    GREP="grep ."
#fi

if [ $CLEAN == "YES" ]
then
    (cd $KINVEYKITLOC && xcodebuild -sdk iphonesimulator -configuration Debug -target KinveyKitTests clean test) #| $GREP
else
    (cd $KINVEYKITLOC && xcodebuild -sdk iphonesimulator -configuration Debug -target KinveyKitTests test) #| $GREP
fi
