//
//  KCSFileStoreTestsSwift.swift
//  KinveyKit
//
//  Created by Victor Barros on 2015-07-10.
//  Copyright (c) 2015 Kinvey. All rights reserved.
//

import UIKit
import XCTest

class KCSFileStoreTestsSwift: KCSTestCase {
    
    var file: KCSFile? = nil

    override func setUp() {
        super.setUp()
        
        KCSClient.sharedClient().initializeKinveyServiceForAppKey(
            "kid_-1WAs8Rh2",
            withAppSecret: "2f355bfaa8cb4f7299e914e8e85d8c98",
            usingOptions: nil
        )
        
        weak var expectationLogin = expectationWithDescription("login")
        
        KCSUser.createAutogeneratedUser(
            nil,
            completion: { (user: KCSUser!, error: NSError!, actionResult: KCSUserActionResult) -> Void in
                XCTAssertNil(error)
                XCTAssertNotNil(user)
                
                expectationLogin?.fulfill()
        })
        
        waitForExpectationsWithTimeout(30, handler: { (error: NSError?) -> Void in
            expectationLogin = nil
        })
    }
    
    override func tearDown() {
        KCSUser.activeUser()?.logout()
        
        super.tearDown()
    }
    
    func upload() {
        weak var expectationUpload = expectationWithDescription("upload")
        
        let url = NSBundle(forClass: self.dynamicType).URLForResource("mavericks", withExtension: "jpg")
        KCSFileStore.uploadFile(
            url,
            options: nil,
            completionBlock: { (file: KCSFile!, error: NSError!) -> Void in
                self.file = file
                
                XCTAssertNil(error)
                XCTAssertNotNil(file)
                
                if let file = file {
                    XCTAssertEqual("https", file.remoteURL.scheme)
                }
                
                XCTAssertTrue(NSThread.isMainThread())
                
                expectationUpload?.fulfill()
            },
            progressBlock: nil
        )
        
        waitForExpectationsWithTimeout(60, handler: { (error: NSError?) -> Void in
            expectationUpload = nil
        })
    }

    func testUpload() {
        upload()
    }
    
    func testDownloadByQuery() {
        upload()
        
        weak var expectationDownload = expectationWithDescription("download")
        
        var query: KCSQuery! = nil
        if let userId = KCSUser.activeUser()?.userId {
            query = KCSQuery(onField: "_acl.creator", withExactMatchForValue: userId)
        } else {
            query = KCSQuery()
        }
        
        KCSFileStore.downloadFileByQuery(
            query,
            completionBlock: { (results: [AnyObject]!, error: NSError!) -> Void in
                XCTAssertNil(error)
                XCTAssertNotNil(results)
                
                if let results = results {
                    XCTAssertGreaterThan(results.count, 0)
                    for file in results as! [KCSFile] {
                        XCTAssertEqual("https", file.remoteURL.scheme)
                    }
                }
                
                XCTAssertTrue(NSThread.isMainThread())
                
                expectationDownload?.fulfill()
            },
            progressBlock: nil
        )
        
        waitForExpectationsWithTimeout(60, handler: nil)
    }
    
    func testDownloadByQuery2() {
        upload()
        
        weak var expectationDownload = expectationWithDescription("download")
        
        let query = KCSQuery(onField: "_filename", withExactMatchForValue: "mavericks.jpg")
        if let userId = KCSUser.activeUser()?.userId {
            query.addQueryOnField("_acl.creator", withExactMatchForValue: userId)
        }
        
        KCSFileStore.downloadFileByQuery(
            query,
            completionBlock: { (results: [AnyObject]!, error: NSError!) -> Void in
                XCTAssertNil(error)
                XCTAssertNotNil(results)
                
                if let results = results {
                    XCTAssertGreaterThan(results.count, 0)
                    for file in results as! [KCSFile] {
                        XCTAssertEqual("https", file.remoteURL.scheme)
                    }
                }
                
                XCTAssertTrue(NSThread.isMainThread())
                
                expectationDownload?.fulfill()
            },
            progressBlock: nil
        )
        
        waitForExpectationsWithTimeout(60, handler: nil)
    }
    
    func testDownloadByName() {
        upload()
        
        weak var expectationDownload = expectationWithDescription("download")
        
        KCSFileStore.downloadFileByName(
            "mavericks.jpg",
            completionBlock: { (results: [AnyObject]!, error: NSError!) -> Void in
                XCTAssertNil(error)
                XCTAssertNotNil(results)
                
                if let results = results {
                    XCTAssertGreaterThan(results.count, 0)
                    for file in results as! [KCSFile] {
                        XCTAssertEqual("https", file.remoteURL.scheme)
                    }
                }
                
                XCTAssertTrue(NSThread.isMainThread())
                
                expectationDownload?.fulfill()
            },
            progressBlock: nil
        )
        
        waitForExpectationsWithTimeout(60, handler: nil)
    }
    
    func testDownloadFile() {
        upload()
        
        XCTAssertNotNil(file)
        
        if let file = file {
            weak var expectationDownload = expectationWithDescription("download")
            
            KCSFileStore.downloadFile(
                file.fileId,
                options: [KCSFileOnlyIfNewer : true],
                completionBlock: { (results: [AnyObject]!, error: NSError!) -> Void in
                    XCTAssertNil(error)
                    XCTAssertNotNil(results)
                    if let results = results {
                        XCTAssertGreaterThan(results.count, 0)
                        
                        for file in results as! [KCSFile] {
                            XCTAssertEqual("https", file.remoteURL.scheme)
                        }
                    }
                    
                    XCTAssertTrue(NSThread.isMainThread())
                    
                    expectationDownload?.fulfill()
                },
                progressBlock: nil
            )
            
            waitForExpectationsWithTimeout(60, handler: nil)
        }
    }

}
