//
//  KCSLogTestsAllDisabled.m
//  KinveyKit
//
//  Created by Victor Barros on 2015-08-20.
//  Copyright (c) 2015 Kinvey. All rights reserved.
//

#import "KCSLogTests.h"
#import <KinveyKit/KinveyKit.h>
#import "KCSLogTestsAllDisabled-Swift.h"

@interface KCSLogTestsAllDisabled : KCSLogTests
@end

@implementation KCSLogTestsAllDisabled

- (void)testAllDisabled {
    [KCSClient configureLoggingWithNetworkEnabled:NO
                                     debugEnabled:NO
                                     traceEnabled:NO
                                   warningEnabled:NO
                                     errorEnabled:NO];
    
    [[KCSClient sharedClient] initializeKinveyServiceForAppKey:@"kid_-1WAs8Rh2"
                                                 withAppSecret:@"2f355bfaa8cb4f7299e914e8e85d8c98"
                                                  usingOptions:nil];
    
    __weak XCTestExpectation* expectationLogin = [self expectationWithDescription:@"login"];
    [KCSUser createAutogeneratedUser:nil
                          completion:^(KCSUser *user, NSError *errorOrNil, KCSUserActionResult result)
     {
         [expectationLogin fulfill];
     }];
    [self waitForExpectationsWithTimeout:30 handler:nil];
    
    KCSQueryBaseTests* test = [[KCSQueryBaseTests alloc] init];
    [test removeByQuery];
    [test queryByDate];
    
    __weak XCTestExpectation *expectationLogVersion = [self expectationWithDescription:@"logVersion"];
    dispatch_after(dispatch_time(DISPATCH_TIME_NOW, (int64_t)(10 * NSEC_PER_SEC)), dispatch_get_main_queue(), ^{
        [expectationLogVersion fulfill];
    });
    [self waitForExpectationsWithTimeout:60 handler:nil];
    XCTAssertEqual(self.logs.count, 0);
}

@end
