//
//  KCSLogTestsAllEnabled.m
//  KinveyKit
//
//  Created by Victor Barros on 2015-08-20.
//  Copyright (c) 2015 Kinvey. All rights reserved.
//

#import "KCSLogTests.h"
#import <KinveyKit/KinveyKit.h>
#import "KCSLogTestsAllEnabled-Swift.h"

@interface KCSLogTestsAllEnabled : KCSLogTests
@end

@implementation KCSLogTestsAllEnabled

- (void)testAllEnabled {
    [KCSClient configureLoggingWithNetworkEnabled:YES
                                     debugEnabled:YES
                                     traceEnabled:YES
                                   warningEnabled:YES
                                     errorEnabled:YES];
    
    [[KCSClient sharedClient] initializeKinveyServiceForAppKey:@"kid_-1WAs8Rh2"
                                                 withAppSecret:@"2f355bfaa8cb4f7299e914e8e85d8c98"
                                                  usingOptions:nil];
    
    __weak XCTestExpectation* expectationLogin = [self expectationWithDescription:@"login"];
    [KCSUser createAutogeneratedUser:nil
                          completion:^(KCSUser *user, NSError *errorOrNil, KCSUserActionResult result)
     {
         [expectationLogin fulfill];
     }];
    [self waitForExpectationsWithTimeout:30 handler:nil];
    
    KCSQueryBaseTests* test = [[KCSQueryBaseTests alloc] init];
    [test removeByQuery];
    [test queryByDate];
    
    __weak __block XCTestExpectation *expectationLogVersion = [self expectationWithDescription:@"logVersion"];
    dispatch_async(dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_BACKGROUND, 0), ^{
        [KCS_DDLog flushLog];
        
        while (expectationLogVersion && self.logs.count < 1) {
        }
        
        XCTAssertTrue([self.logs[0] containsString:@"Kinvey iOS Library Version"], @"Actual Result: %@", self.logs.lastObject);
        
        [expectationLogVersion fulfill];
    });
    [self waitForExpectationsWithTimeout:60 handler:^(NSError *error) {
        expectationLogVersion = nil;
    }];
}

@end
