//
//  KCSUserTests.swift
//  KinveyKit
//
//  Created by Victor Barros on 2015-08-10.
//  Copyright (c) 2015 Kinvey. All rights reserved.
//

import UIKit
import XCTest

class KCSUserTests: KCSTestCase {

    override func setUp() {
        super.setUp()
        
        KCSClient.sharedClient().initializeKinveyServiceForAppKey(
            "kid_-1WAs8Rh2",
            withAppSecret: "2f355bfaa8cb4f7299e914e8e85d8c98",
            usingOptions: nil
        )
    }
    
    override func tearDown() {
        KCSUser.activeUser()?.logout()
        
        super.tearDown()
    }

    func testCreateAutogeneratedUser() {
        weak var expectationCreate = expectationWithDescription("create")
        
        KCSUser.createAutogeneratedUser(
            nil,
            completion: { (user: KCSUser!, error: NSError!, actionResult: KCSUserActionResult) -> Void in
                XCTAssertTrue(NSThread.isMainThread())
                
                expectationCreate?.fulfill()
            }
        )
        
        waitForExpectationsWithTimeout(30, handler: { (error: NSError?) -> Void in
            expectationCreate = nil
        })
    }
    
    func testCreateAutogeneratedUserCancel() {
        weak var expectationCreate = expectationWithDescription("create")
        
        var executed = false
        let request = KCSUser.createAutogeneratedUser(
            nil,
            completion: { (user: KCSUser!, error: NSError!, actionResult: KCSUserActionResult) -> Void in
                executed = true
                
                XCTAssertTrue(NSThread.isMainThread())
                
                expectationCreate?.fulfill()
            }
        )
        
        XCTAssertFalse(request.cancelled)
        
        request.cancellationBlock = {
            expectationCreate?.fulfill()
        }
        
        request.cancel()
        
        XCTAssertTrue(request.cancelled)
        
        waitForExpectationsWithTimeout(30, handler: { (error: NSError?) -> Void in
            expectationCreate = nil
        })
        
        XCTAssertFalse(executed)
    }
    
    func createUser() {
        weak var expectationCreate = expectationWithDescription("create")
        
        KCSUser.createAutogeneratedUser(
            nil,
            completion: { (user: KCSUser!, error: NSError!, actionResult: KCSUserActionResult) -> Void in
                XCTAssertNotNil(user)
                XCTAssertNil(error)
                
                XCTAssertTrue(NSThread.isMainThread())
                
                expectationCreate?.fulfill()
            }
        )
        
        waitForExpectationsWithTimeout(30, handler: { (error: NSError?) -> Void in
            expectationCreate = nil
        })
    }
    
    func testRefreshUser() {
        createUser()
        
        if let user = KCSUser.activeUser() {
            weak var expectationRefresh = expectationWithDescription("refresh")
            
            user.refreshFromServer { (result: [AnyObject]!, error: NSError!) -> Void in
                XCTAssertTrue(NSThread.isMainThread())
                
                expectationRefresh?.fulfill()
            }
            
            waitForExpectationsWithTimeout(30, handler: { (error: NSError?) -> Void in
                expectationRefresh = nil
            })
        }
    }
    
    func testRefreshUserCancel() {
        createUser()
        
        if let user = KCSUser.activeUser() {
            weak var expectationRefresh = expectationWithDescription("refresh")
            
            let request = user.refreshFromServer { (result: [AnyObject]!, error: NSError!) -> Void in
                XCTAssertTrue(NSThread.isMainThread())
                XCTFail()
                
                expectationRefresh?.fulfill()
            }
            
            XCTAssertFalse(request.cancelled)
            
            request.cancellationBlock = {
                expectationRefresh?.fulfill()
            }
            
            request.cancel()
            
            XCTAssertTrue(request.cancelled)
            
            waitForExpectationsWithTimeout(30, handler: { (error: NSError?) -> Void in
                expectationRefresh = nil
            })
        }
    }
    
    func testChangePassword() {
        createUser()
        
        if let user = KCSUser.activeUser() {
            weak var expectationChangePassword = expectationWithDescription("changePassword")
            
            user.changePassword(
                "1234",
                completionBlock: { (results: [AnyObject]!, error: NSError!) -> Void in
                    XCTAssertTrue(NSThread.isMainThread())
                    
                    expectationChangePassword?.fulfill()
                }
            )
            
            waitForExpectationsWithTimeout(30, handler: { (error: NSError?) -> Void in
                expectationChangePassword = nil
            })
        }
    }
    
    func testChangePasswordCancel() {
        createUser()
        
        if let user = KCSUser.activeUser() {
            weak var expectationChangePassword = expectationWithDescription("changePassword")
            
            let request = user.changePassword(
                "1234",
                completionBlock: { (results: [AnyObject]!, error: NSError!) -> Void in
                    XCTAssertTrue(NSThread.isMainThread())
                    
                    expectationChangePassword?.fulfill()
                }
            )
            
            XCTAssertFalse(request.cancelled)
            
            request.cancellationBlock = {
                expectationChangePassword?.fulfill()
            }
            
            request.cancel()
            
            XCTAssertTrue(request.cancelled)
            
            waitForExpectationsWithTimeout(30, handler: { (error: NSError?) -> Void in
                expectationChangePassword = nil
            })
        }
    }
    
    func testSaveUser() {
        createUser()
        
        if let user = KCSUser.activeUser() {
            weak var expectationSaveUser = expectationWithDescription("saveUser")
            
            user.saveWithCompletionBlock { (results: [AnyObject]!, error: NSError!) -> Void in
                XCTAssertTrue(NSThread.isMainThread())
                
                expectationSaveUser?.fulfill()
            }
            
            waitForExpectationsWithTimeout(30, handler: { (error: NSError?) -> Void in
                expectationSaveUser = nil
            })
        }
    }
    
    func testSaveUserCancel() {
        createUser()
        
        if let user = KCSUser.activeUser() {
            weak var expectationSaveUser = expectationWithDescription("saveUser")
            
            let request = user.saveWithCompletionBlock { (results: [AnyObject]!, error: NSError!) -> Void in
                XCTAssertTrue(NSThread.isMainThread())
                XCTFail()
                
                expectationSaveUser?.fulfill()
            }
            
            XCTAssertFalse(request.cancelled)
            
            request.cancellationBlock = {
                expectationSaveUser?.fulfill()
            }
            
            request.cancel()
            
            XCTAssertTrue(request.cancelled)
            
            waitForExpectationsWithTimeout(30, handler: { (error: NSError?) -> Void in
                expectationSaveUser = nil
            })
        }
    }
    
    func testDeleteUser() {
        createUser()
        
        if let user = KCSUser.activeUser() {
            weak var expectationDeleteUser = expectationWithDescription("deleteUser")
            
            user.removeWithCompletionBlock { (results: [AnyObject]!, error: NSError!) -> Void in
                XCTAssertTrue(NSThread.isMainThread())
                
                expectationDeleteUser?.fulfill()
            }
            
            waitForExpectationsWithTimeout(30, handler: { (error: NSError?) -> Void in
                expectationDeleteUser = nil
            })
        }
    }
    
    func testDeleteUserCancel() {
        createUser()
        
        if let user = KCSUser.activeUser() {
            weak var expectationDeleteUser = expectationWithDescription("deleteUser")
            
            let request = user.removeWithCompletionBlock { (results: [AnyObject]!, error: NSError!) -> Void in
                XCTAssertTrue(NSThread.isMainThread())
                XCTFail()
                
                expectationDeleteUser?.fulfill()
            }
            
            XCTAssertFalse(request.cancelled)
            
            request.cancellationBlock = {
                expectationDeleteUser?.fulfill()
            }
            
            request.cancel()
            
            XCTAssertTrue(request.cancelled)
            
            waitForExpectationsWithTimeout(30, handler: { (error: NSError?) -> Void in
                expectationDeleteUser = nil
            })
        }
    }

}
